name: Continuos Integration workflow

on: pull_request

jobs:
  ci-menu-public-portal:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/manfred2word
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install
        run: |
          npm pkg delete scripts.prepare
          npm ci
      - name: Tests
        run: npm test
